apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # This URL uses Docker's internal DNS to resolve the Prometheus container
    url: http://prometheus:9090
    isDefault: true
    editable: false
