"""change provider to provider_name on notifications table

Revision ID: 4f1ac0150253
Revises: 58f6b0c92e1a
Create Date: 2026-05-26 10:09:47.477887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1ac0150253'
down_revision: Union[str, Sequence[str], None] = '58f6b0c92e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('provider_name', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('recurrence_rule', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('timezone', sa.String(length=50), nullable=False))
    op.drop_column('notifications', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('notifications', 'timezone')
    op.drop_column('notifications', 'recurrence_rule')
    op.drop_column('notifications', 'provider_name')
    # ### end Alembic commands ###
