"""add provider_message_id

Revision ID: 7f36afcf6b08
Revises: 14b3526ee0b4
Create Date: 2026-05-24 23:11:56.766931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f36afcf6b08'
down_revision: Union[str, Sequence[str], None] = '14b3526ee0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('provider_message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_provider_message_id'), 'notifications', ['provider_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_provider_message_id'), table_name='notifications')
    op.drop_column('notifications', 'provider_message_id')
    # ### end Alembic commands ###
