"""update user preference schema

Revision ID: e3f97acdb984
Revises: 4f1ac0150253
Create Date: 2026-05-26 21:51:53.448953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f97acdb984'
down_revision: Union[str, Sequence[str], None] = '4f1ac0150253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('dnd', sa.Boolean(), nullable=False))
    op.add_column('user_preferences', sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('user_preferences', sa.Column('templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('user_preferences', 'unsubscribed_channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('unsubscribed_channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('user_preferences', 'templates')
    op.drop_column('user_preferences', 'channels')
    op.drop_column('user_preferences', 'dnd')
    # ### end Alembic commands ###
