from abc import ABC, abstractmethod
from typing import Dict, Any, Optional


class ProviderError(Exception):
    """
    A generic exception raised when a third-party provider fails.
    Concrete adapters (e.g., TwilioSMSProvider) must catch their own SDK errors
    and raise this instead, so the core logic can handle all provider errors uniformly.
    """
    def __init__(self, message: str, provider_name: str, status_code: Optional[int] = None):
        super().__init__(message)
        self.provider_name = provider_name
        self.status_code = status_code


class EmailProvider(ABC):
    """Contract for sending Email notifications."""
    
    @abstractmethod
    def send(
        self, 
        recipient_email: str, 
        subject: str,
        body_text: str,
        template_id: Optional[str] = None, 
        template_data: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Dispatches an email.
        
        Returns:
            str: The unique message ID generated by the provider (used for webhook tracking).
            
        Raises:
            ProviderError: If the dispatch fails.
        """
        pass


class SMSProvider(ABC):
    """Contract for sending SMS notifications."""
    
    @abstractmethod
    def send(self, phone_number: str, message: str) -> str:
        """
        Dispatches an SMS.
        
        Returns:
            str: The unique message ID generated by the provider.
            
        Raises:
            ProviderError: If the dispatch fails.
        """
        pass


class PushProvider(ABC):
    """Contract for sending OS-level Mobile Push Notifications."""
    
    @abstractmethod
    def send(
        self, 
        device_token: str, 
        title: str, 
        body: str, 
        data: Optional[Dict[str, str]] = None
    ) -> str:
        """
        Dispatches a push notification to a device.
        
        Returns:
            str: Unique message ID generated by the provider.
            
        Raises:
            ProviderError: If the dispatch fails.
        """
        pass
